## FragmentShader Shader ##
#=
:: mandatory
>> fragment data generated by the rasterizer
   execute for each fragment(pixel)
   fragment’s color and depth values are computed
<< processed fragment data
=#

# Note that you may need to modify the version number(e.g. 410 here) to fit your specific case.

triangle♡f = """#version 410 core
                out vec4 color;
                void main(void)
                {
                    color = vec4(1.0, 0.0, 0.0, 1.0);
                }"""

triangle♠f = """#version 410 core
                // 'in's
                // interface block
                in TriangleColor
                {
                    vec4 color;
                }trianglecolor;

                // 'out's
                out vec4 color;

                void main(void)
                {
                    color = trianglecolor.color;
                }"""

triangle♢f = """#version 410 core
                // uniforms
                uniform vec4 ucolor;

                // 'out's
                out vec4 color;

                void main(void)
                {
                    color = ucolor;
                }"""

triangle♣f = """#version 410 core
                // uniform blocks
                layout (binding = 0) uniform FuzzyTriangle
                {
                    vec4 InnerColor;
                    vec4 OuterColor;
                    float RadiusInner;
                    float RadiusOuter;
                };

                // 'out's
                out vec4 color;

                void main(void)
                {
                    dx = gl_FragCoord.x;
                    dy = gl_FragCoord.y;
                    dist = sqrt( dx*dx, dy*dy);
                    color = mix( InnerColor, OuterColor, smoothstep( RadiusInner, RadiusOuter, dist) );
                }"""
